//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels_app.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotels_app.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host=localhost;Port=5432;Database=hotels_db;Username=postgres;Password=THEWORLD;SslMode=Prefer;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить.
        /// </summary>
        internal static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить отель.
        /// </summary>
        internal static string TextAddHotel {
            get {
                return ResourceManager.GetString("TextAddHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вернуться к отелям.
        /// </summary>
        internal static string TextBackToHotels {
            get {
                return ResourceManager.GetString("TextBackToHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на забронировать.
        /// </summary>
        internal static string TextBook {
            get {
                return ResourceManager.GetString("TextBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на забронированные.
        /// </summary>
        internal static string TextBooked {
            get {
                return ResourceManager.GetString("TextBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отменить
        ///бронирование.
        /// </summary>
        internal static string TextCancelBooking {
            get {
                return ResourceManager.GetString("TextCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить.
        /// </summary>
        internal static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УДАЛИТЬ АККАУНТ.
        /// </summary>
        internal static string TextDeleteAccount {
            get {
                return ResourceManager.GetString("TextDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить отель.
        /// </summary>
        internal static string TextDeleteHotel {
            get {
                return ResourceManager.GetString("TextDeleteHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на редактировать.
        /// </summary>
        internal static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на редактировать
        ///аккаунт.
        /// </summary>
        internal static string TextEditAccount {
            get {
                return ResourceManager.GetString("TextEditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОЙТИ.
        /// </summary>
        internal static string TextEnter {
            get {
                return ResourceManager.GetString("TextEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пройти анкету.
        /// </summary>
        internal static string TextOpenQuestionnaire {
            get {
                return ResourceManager.GetString("TextOpenQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАРЕГИСТРИРОВАТЬСЯ.
        /// </summary>
        internal static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НОМЕРА.
        /// </summary>
        internal static string TextRooms {
            get {
                return ResourceManager.GetString("TextRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сохранить.
        /// </summary>
        internal static string TextSaveLower {
            get {
                return ResourceManager.GetString("TextSaveLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОХРАНИТЬ.
        /// </summary>
        internal static string TextSaveUpper {
            get {
                return ResourceManager.GetString("TextSaveUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЫБРАТЬ.
        /// </summary>
        internal static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на загрузить
        ///картинку.
        /// </summary>
        internal static string TextUploadImage {
            get {
                return ResourceManager.GetString("TextUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на x.
        /// </summary>
        internal static string TextX {
            get {
                return ResourceManager.GetString("TextX", resourceCulture);
            }
        }
    }
}
