//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels_app.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotels_app.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить этот отель и все связанные с ним номера? Это действие нельзя отменить..
        /// </summary>
        internal static string Confirm_DeleteHotel {
            get {
                return ResourceManager.GetString("Confirm_DeleteHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=2343;SslMode=Prefer;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование отелей.
        /// </summary>
        internal static string EditHotels {
            get {
                return ResourceManager.GetString("EditHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один номер для отеля..
        /// </summary>
        internal static string Error_AddAtLeastOneRoom {
            get {
                return ResourceManager.GetString("Error_AddAtLeastOneRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при добавлении номера: {0}.
        /// </summary>
        internal static string Error_AddRoomException {
            get {
                return ResourceManager.GetString("Error_AddRoomException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить изображение..
        /// </summary>
        internal static string Error_ImageUploadFailed {
            get {
                return ResourceManager.GetString("Error_ImageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка.
        /// </summary>
        internal static string Error_mes {
            get {
                return ResourceManager.GetString("Error_mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, заполните все обязательные поля.
        /// </summary>
        internal static string Error_RequiredFields {
            get {
                return ResourceManager.GetString("Error_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комната с таким названием уже существует.
        /// </summary>
        internal static string Error_RoomExists {
            get {
                return ResourceManager.GetString("Error_RoomExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось найти выбранный номер..
        /// </summary>
        internal static string Error_RoomNotFound {
            get {
                return ResourceManager.GetString("Error_RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите номер для удаления..
        /// </summary>
        internal static string Error_SelectRoomToDelete {
            get {
                return ResourceManager.GetString("Error_SelectRoomToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город \&quot;{0}\&quot; не найден в базе данных. Выберите существующий город..
        /// </summary>
        internal static string FalseCity {
            get {
                return ResourceManager.GetString("FalseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image Files|.jpg;.jpeg;.png;.bmp;*.gif.
        /// </summary>
        internal static string ImageFilesFilter {
            get {
                return ResourceManager.GetString("ImageFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите изображение.
        /// </summary>
        internal static string SelectImageTitle {
            get {
                return ResourceManager.GetString("SelectImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отель и номера успешно добавлены!.
        /// </summary>
        internal static string Success_HotelAdded {
            get {
                return ResourceManager.GetString("Success_HotelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отель и все связанные номера успешно удалены.
        /// </summary>
        internal static string Success_HotelDeleted {
            get {
                return ResourceManager.GetString("Success_HotelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отель успешно обновлен!.
        /// </summary>
        internal static string Success_HotelUpdated {
            get {
                return ResourceManager.GetString("Success_HotelUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер успешно добавлен!.
        /// </summary>
        internal static string Success_RoomAdded {
            get {
                return ResourceManager.GetString("Success_RoomAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер успешно удален..
        /// </summary>
        internal static string Success_RoomDeleted {
            get {
                return ResourceManager.GetString("Success_RoomDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить.
        /// </summary>
        internal static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавить отель.
        /// </summary>
        internal static string TextAddHotel {
            get {
                return ResourceManager.GetString("TextAddHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вернуться к отелям.
        /// </summary>
        internal static string TextBackToHotels {
            get {
                return ResourceManager.GetString("TextBackToHotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на забронировать.
        /// </summary>
        internal static string TextBook {
            get {
                return ResourceManager.GetString("TextBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на забронированные.
        /// </summary>
        internal static string TextBooked {
            get {
                return ResourceManager.GetString("TextBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отменить
        ///бронирование.
        /// </summary>
        internal static string TextCancelBooking {
            get {
                return ResourceManager.GetString("TextCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить.
        /// </summary>
        internal static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УДАЛИТЬ АККАУНТ.
        /// </summary>
        internal static string TextDeleteAccount {
            get {
                return ResourceManager.GetString("TextDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удалить отель.
        /// </summary>
        internal static string TextDeleteHotel {
            get {
                return ResourceManager.GetString("TextDeleteHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на редактировать.
        /// </summary>
        internal static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на редактировать
        ///аккаунт.
        /// </summary>
        internal static string TextEditAccount {
            get {
                return ResourceManager.GetString("TextEditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОЙТИ.
        /// </summary>
        internal static string TextEnter {
            get {
                return ResourceManager.GetString("TextEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пройти анкету.
        /// </summary>
        internal static string TextOpenQuestionnaire {
            get {
                return ResourceManager.GetString("TextOpenQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАРЕГИСТРИРОВАТЬСЯ.
        /// </summary>
        internal static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НОМЕРА.
        /// </summary>
        internal static string TextRooms {
            get {
                return ResourceManager.GetString("TextRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сохранить.
        /// </summary>
        internal static string TextSaveLower {
            get {
                return ResourceManager.GetString("TextSaveLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОХРАНИТЬ.
        /// </summary>
        internal static string TextSaveUpper {
            get {
                return ResourceManager.GetString("TextSaveUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЫБРАТЬ.
        /// </summary>
        internal static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на загрузить
        ///картинку.
        /// </summary>
        internal static string TextUploadImage {
            get {
                return ResourceManager.GetString("TextUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на x.
        /// </summary>
        internal static string TextX {
            get {
                return ResourceManager.GetString("TextX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        internal static string Title_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Title_DeleteConfirmation", resourceCulture);
            }
        }
    }
}
